name: Upload Python Package

on:
  push:
    paths:
      - "pyproject.toml"  # 仅监控 pyproject.toml 文件的更改

permissions:
  contents: read

jobs:
  check-version-change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check version change
        id: version-check
        run: |
          # 提取当前版本号
          current_version=$(grep -E '^version\s*=\s*".+"' pyproject.toml | sed -E 's/version\s*=\s*"([^"]+)"/\1/')
          
          # 提取之前版本号
          previous_version=$(git show HEAD~1:pyproject.toml | grep -E '^version\s*=\s*".+"' | sed -E 's/version\s*=\s*"([^"]+)"/\1/')
          
          # 输出版本号到 GitHub 环境变量
          echo "current_version=$current_version" >> $GITHUB_ENV
          echo "previous_version=$previous_version" >> $GITHUB_ENV
          
          # 比较版本号，如果相同则中止工作流
          if [[ "$current_version" == "$previous_version" ]]; then
            echo "Version has not changed."
            exit 1  # 中止工作流，因为版本号没有变动
          else
            echo "Version has changed: $previous_version -> $current_version"
          fi

  release-build:
    runs-on: ubuntu-latest
    needs: check-version-change

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
          repository-url: https://pypi.org/legacy/
          password: ${{ secrets.PYPI_APIKEY }}
